[package]
name = "image_to_ascii"
version = "0.1.0"
authors = ["blowin <dsessence@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
clap = "2.26.0"

[profile.release]
opt-level = 3
debug = false
